import { useState } from 'react';
import Head from 'next/head';
import Table from '../components/table';
import fetch from 'isomorphic-unfetch';
import styled from 'styled-components';
import Sorting from '../components/sorting';
import AddButton from '../components/AddButton';
import AddItem from '../components/AddItem';

const Title_style = styled.div`
  div {
    width: 100vw;
    height: 70px;
    display: flex;
    justify-content: center;
    align-items: center;
    background-color: black;
  }
  h1 {
    color: #fff;
    font-size: 36px;
  }
`
export default function Home({ data }) {

  const [isAdding, setIsAdding] = useState(false);

  return (
    <>
      <Head>
        <title>Таблица грузоперевозок</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      <Title_style>
        <div>
          <h1>Таблица грузоперевозок</h1>
        </div>
      </Title_style>

      <div className='screen'>
        <div className='wrapper'>

          <div className='head'>
            <Sorting />
            <AddButton isAdding={isAdding} setIsAdding={setIsAdding} />
          </div>

          {isAdding && <AddItem />}

          <Table data={data.data} />
        </div>
      </div>
    </>
  )
}

Home.getInitialProps = async () => {
  const res = await fetch(`http://localhost:3000/api/table`);
  const data = await res.json()

  if (!data) {
    return {
      notFound: true,
    }
  }

  return { data }
}